-- Auto-generated from schema-map-postgres.yaml (map@4ae85c5)
-- engine: postgres
-- table:  deletion_jobs

CREATE TABLE IF NOT EXISTS deletion_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk    VARCHAR(64) NOT NULL,
  reason TEXT NULL,
  hard_delete BOOLEAN NOT NULL DEFAULT FALSE,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  error TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_deletion_jobs UNIQUE (entity_table, entity_pk),
  CONSTRAINT chk_dj_status CHECK (status IN ('pending','running','done','failed','cancelled'))
);
